name: Node.js CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # Versions de Node.js à tester
    steps:
      # Vérification du code
      - name: Checkout code
        uses: actions/checkout@v2

      # Configuration de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Installation des dépendances
      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Start server
        run: npm start &

      # Exécution du script tests.sh
      - name: Run tests.sh script
        run: chmod +x ./tests.sh && ./tests.sh
