name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3

    - name: Install dependencies
      run: npm install

    - name: Rebuild bcrypt
      run: npm rebuild bcrypt --build-from-source

    - name: Start server
      run: npm start &
      
    - name: Wait for server to be ready
      run: sleep 5

    - name: Run tests
      run: chmod +x ./tests.sh && ./tests.sh
